import frappe
from frappe.tests import IntegrationTestCase

from personal_expense_tracker.api import (
	get_category_budget_dashboard,
	get_category_budget_status,
)


class TestCategoryBudgetDashboard(IntegrationTestCase):
	def setUp(self):
		frappe.set_user("Administrator")
		self.cleanup_test_records()
		self.user = "Administrator"
		self.suffix = frappe.generate_hash(length=8)
		self.period = self.create_budget_period()
		self.create_income(10_000_000)

	def tearDown(self):
		self.cleanup_test_records()
		frappe.db.commit()

	def cleanup_test_records(self):
		delete_specs = [
			("Expense Entry", {"category": ["like", "PET Test %"]}),
			("Monthly Budget", {"category": ["like", "PET Test %"]}),
			("Income Entry", {"description": "Test income"}),
			("Expense Category", {"name": ["like", "PET Test %"]}),
			("Budget Period", {"name": ["like", "PET Test Period %"]}),
		]
		for doctype, filters in delete_specs:
			for name in frappe.get_all(doctype, filters=filters, pluck="name"):
				frappe.delete_doc(doctype, name, ignore_permissions=True, force=True)

	def create_budget_period(self):
		return frappe.get_doc(
			{
				"doctype": "Budget Period",
				"period_name": f"PET Test Period {self.suffix}",
				"status": "Open",
				"from_date": "2024-01-01",
				"to_date": "2024-01-31",
				"month": "January",
				"year": 2026,
				"notes": "Generated by category budget dashboard tests.",
			}
		).insert(ignore_permissions=True)

	def create_category(self, label, default_budget=0):
		return frappe.get_doc(
			{
				"doctype": "Expense Category",
				"category_name": f"PET Test {label} {self.suffix}",
				"is_active": 1,
				"monthly_budget": default_budget,
			}
		).insert(ignore_permissions=True)

	def create_income(self, amount):
		return frappe.get_doc(
			{
				"doctype": "Income Entry",
				"posting_date": "2024-01-02",
				"user": self.user,
				"income_source": "Paycheck",
				"description": "Test income",
				"amount": amount,
				"currency": "SYP",
				"exchange_rate_to_base": 1,
				"base_currency": "SYP",
			}
		).insert(ignore_permissions=True)

	def create_budget(self, category, amount, currency="SYP", exchange_rate=1):
		return frappe.get_doc(
			{
				"doctype": "Monthly Budget",
				"user": self.user,
				"budget_period": self.period.name,
				"category": category.name,
				"budget_amount": amount,
				"currency": currency,
				"exchange_rate_to_base": exchange_rate,
			}
		).insert(ignore_permissions=True)

	def create_expense(self, category, amount, currency="SYP", exchange_rate=1):
		return frappe.get_doc(
			{
				"doctype": "Expense Entry",
				"posting_date": "2024-01-05",
				"user": self.user,
				"category": category.name,
				"description": "Test expense",
				"amount": amount,
				"currency": currency,
				"exchange_rate_to_base": exchange_rate,
				"base_currency": "SYP",
				"payment_method": "Cash",
			}
		).insert(ignore_permissions=True)

	def test_budget_status_thresholds_and_no_budget(self):
		scenarios = {
			"safe": (500, "safe"),
			"warning": (800, "warning"),
			"danger": (950, "danger"),
			"exceeded": (1200, "exceeded"),
		}

		for label, (spend, expected_status) in scenarios.items():
			category = self.create_category(label)
			self.create_budget(category, 1000)
			self.create_expense(category, spend)

			status = get_category_budget_status(
				user=self.user,
				category=category.name,
				budget_period=self.period.name,
			)
			self.assertEqual(status.status, expected_status)
			self.assertEqual(status.budget, 1000)
			self.assertEqual(status.spent, spend)

		category_without_budget = self.create_category("no budget", default_budget=2500)
		self.create_expense(category_without_budget, 300)
		status = get_category_budget_status(
			user=self.user,
			category=category_without_budget.name,
			budget_period=self.period.name,
		)
		self.assertEqual(status.status, "no_budget")
		self.assertEqual(status.budget_source, "default_category_budget")
		self.assertEqual(status.budget, 0)
		self.assertEqual(status.default_budget, 2500)

	def test_multicurrency_budget_uses_base_values(self):
		category = self.create_category("multicurrency")
		self.create_budget(category, 100, currency="USD", exchange_rate=14000)
		self.create_expense(category, 50, currency="USD", exchange_rate=14000)

		status = get_category_budget_status(
			user=self.user,
			category=category.name,
			budget_period=self.period.name,
		)
		self.assertEqual(status.status, "safe")
		self.assertEqual(status.budget, 1_400_000)
		self.assertEqual(status.spent, 700_000)
		self.assertEqual(status.usage_percent, 50)

	def test_dashboard_separates_budgeted_and_unbudgeted_spending(self):
		budgeted_category = self.create_category("dashboard budgeted")
		unbudgeted_category = self.create_category("dashboard unbudgeted")
		self.create_budget(budgeted_category, 1000)
		self.create_expense(budgeted_category, 400)
		self.create_expense(unbudgeted_category, 250)

		dashboard = get_category_budget_dashboard(budget_period=self.period.name, user=self.user)
		rows = {row["category"]: row for row in dashboard["categories"]}

		self.assertEqual(rows[budgeted_category.name]["status"], "safe")
		self.assertEqual(rows[budgeted_category.name]["remaining"], 600)
		self.assertEqual(rows[unbudgeted_category.name]["status"], "no_budget")
		self.assertEqual(dashboard["summary"]["total_allocated"], 1000)
		self.assertEqual(dashboard["summary"]["total_spent"], 400)
		self.assertEqual(dashboard["summary"]["total_unbudgeted"], 250)
		self.assertEqual(dashboard["summary"]["total_remaining"], 600)
